TODO: "Fix text in analytics so there is not so much text"
TODO: "Add more charts to analytics, e.g. a breakdown of mental load by category (chores, childcare, etc.)"
TODO: "Legend outside of chart on all charts, to avoid overlap and make it more readable in AnalyticsSummary"

# CALENDAR
TODO: "Click “Upcoming” → auto-focus that day"
TODO: "Click on event → open details (same as when clicking from task list)"
TODO: "Add a subtle “Today” button"
TODO: "Show number badge instead of amount of dots"
TODO: "Add option to show/hide completed tasks in calendar"
TODO: "Add “Overdue” section above Upcoming"
TODO: "Add soft hover animation to calendar days"
TODO: " Household filter chips (power feature), Add small colored chips above calendar:, [ All ] [ Rebeckas ] [ Larsson–Nguyen ]"
TODO: "Add subtle heat intensity to calendar days based on number of tasks due"
TODO: "Add keyboard navigation"
TODO: "Add a subtle smart insights section above the calendar, e.g. “You have 3 tasks due this week, which is 20% more than your average week"