export const GOAL_TYPES = [
    "savings",
    "weight",
    "training",
    "tasks",
    "reading",
    "meditation",
    "revenue",
    "hydration",
    "learning",
    "streak",
];

export const TRACKING_STYLES = ["daily", "weekly", "total"];

export const goalTemplates = [
    {
        id: "savings",
        name: "Savings Goal",
        description: "Track your savings with a filling jar visualization",
        icon: "🏦",
        color: "sage",
        unit: "$",
        defaultTarget: 1000,
        trackingStyle: "total",
    },
    {
        id: "weight",
        name: "Weight Loss Journey",
        description: "Watch a person walk towards their goal with each kg lost",
        icon: "🏃",
        color: "terracotta",
        unit: "kg",
        defaultTarget: 10,
        trackingStyle: "total",
    },
    {
        id: "training",
        name: "Weekly Training",
        description: "Track your workouts with a weekly habit grid",
        icon: "💪",
        color: "sky",
        unit: "workouts",
        defaultTarget: 4,
        trackingStyle: "weekly",
    },
    {
        id: "tasks",
        name: "Daily Tasks",
        description: "Grow a plant as you complete your daily tasks",
        icon: "🌱",
        color: "sage",
        unit: "tasks",
        defaultTarget: 5,
        trackingStyle: "daily",
    },
    {
        id: "reading",
        name: "Reading Goal",
        description: "Fill your bookshelf as you read more books",
        icon: "📚",
        color: "lavender",
        unit: "books",
        defaultTarget: 12,
        trackingStyle: "total",
    },
    {
        id: "meditation",
        name: "Meditation Streak",
        description: "Watch the moon go from new to full with your streak",
        icon: "🧘",
        color: "lavender",
        unit: "days",
        defaultTarget: 30,
        trackingStyle: "total",
    },
    {
        id: "revenue",
        name: "Revenue Target",
        description: "Launch a rocket as you hit your revenue milestones",
        icon: "🚀",
        color: "terracotta",
        unit: "$",
        defaultTarget: 10000,
        trackingStyle: "total",
    },
    {
        id: "hydration",
        name: "Daily Hydration",
        description: "Fill your water bottle throughout the day",
        icon: "💧",
        color: "sky",
        unit: "glasses",
        defaultTarget: 8,
        trackingStyle: "daily",
    },
    {
        id: "learning",
        name: "Learning Path",
        description: "Unlock nodes on your skill tree as you learn",
        icon: "⚡",
        color: "sage",
        unit: "lessons",
        defaultTarget: 9,
        trackingStyle: "total",
    },
    {
        id: "streak",
        name: "Consistency Streak",
        description: "Keep the flame burning with your daily streak",
        icon: "🔥",
        color: "terracotta",
        unit: "days",
        defaultTarget: 30,
        trackingStyle: "total",
    },
];